import * as THREE from "three";

export const EARTH_RADIUS = 0.38;
export const MOON_RADIUS_RATIO = 0.273;
export const MOON_DISTANCE_RATIO = 60.3;
export const MERCURY_RADIUS_RATIO = 0.383;
export const VENUS_RADIUS_RATIO = 0.949;
export const MARS_RADIUS_RATIO = 0.532;
export const JUPITER_RADIUS_RATIO = 2.8;
export const SATURN_RADIUS_RATIO = 2.33;
export const URANUS_RADIUS_RATIO = 1.01;
export const NEPTUNE_RADIUS_RATIO = 0.98;
export const IO_RADIUS_RATIO = 0.286;
export const EUROPA_RADIUS_RATIO = 0.245;
export const GANYMEDE_RADIUS_RATIO = 0.413;
export const CALLISTO_RADIUS_RATIO = 0.378;
export const TITAN_RADIUS_RATIO = 0.404;
export const MERCURY_ORBIT_DISTANCE_RATIO = 0.387;
export const VENUS_ORBIT_DISTANCE_RATIO = 0.723;
export const MARS_ORBIT_DISTANCE_RATIO = 1.524;
export const JUPITER_ORBIT_DISTANCE_RATIO = 5.203;
export const SATURN_ORBIT_DISTANCE_RATIO = 9.537;
export const URANUS_ORBIT_DISTANCE_RATIO = 19.191;
export const NEPTUNE_ORBIT_DISTANCE_RATIO = 30.07;
export const DISTANCE_COMPRESSION = 0.09;
export const MOON_ORBIT_RADIUS = MOON_DISTANCE_RATIO * DISTANCE_COMPRESSION;
export const JUPITER_MOON_DISTANCE_COMPRESSION = 0.32;
export const SATURN_MOON_DISTANCE_COMPRESSION = 0.4;

export const EARTH_DAY_SECONDS = 23 + 56 / 60;
export const MOON_ORBIT_PERIOD_DAYS = 27.321661;
export const EARTH_ORBIT_PERIOD_DAYS = 365.256363004;
export const MERCURY_ORBIT_PERIOD_DAYS = 87.9691;
export const VENUS_ORBIT_PERIOD_DAYS = 224.701;
export const MARS_ORBIT_PERIOD_DAYS = 686.98;
export const JUPITER_ORBIT_PERIOD_DAYS = 4332.59;
export const SATURN_ORBIT_PERIOD_DAYS = 10759.22;
export const URANUS_ORBIT_PERIOD_DAYS = 30688.5;
export const NEPTUNE_ORBIT_PERIOD_DAYS = 60182;
export const IO_ORBIT_PERIOD_DAYS = 1.769;
export const EUROPA_ORBIT_PERIOD_DAYS = 3.551;
export const GANYMEDE_ORBIT_PERIOD_DAYS = 7.155;
export const CALLISTO_ORBIT_PERIOD_DAYS = 16.689;
export const TITAN_ORBIT_PERIOD_DAYS = 15.945;
export const MERCURY_ROTATION_PERIOD_HOURS = 1407.6;
export const VENUS_ROTATION_PERIOD_HOURS = 5832.5;
export const VENUS_CLOUD_ROTATION_PERIOD_HOURS = 96;
export const MARS_ROTATION_PERIOD_HOURS = 24.6229;
export const JUPITER_ROTATION_PERIOD_HOURS = 9.925;
export const SATURN_ROTATION_PERIOD_HOURS = 10 + 33 / 60;
export const URANUS_ROTATION_PERIOD_HOURS = 17 + 14 / 60;
export const NEPTUNE_ROTATION_PERIOD_HOURS = 16.11;

export const EARTH_ROTATION_SPEED = (Math.PI * 2) / EARTH_DAY_SECONDS;
export const MERCURY_ROTATION_SPEED =
  (Math.PI * 2) / MERCURY_ROTATION_PERIOD_HOURS;
export const VENUS_ROTATION_SPEED =
  (-Math.PI * 2) / VENUS_ROTATION_PERIOD_HOURS;
export const VENUS_CLOUD_ROTATION_SPEED =
  (Math.PI * 2) / VENUS_CLOUD_ROTATION_PERIOD_HOURS;
export const MARS_ROTATION_SPEED = (Math.PI * 2) / MARS_ROTATION_PERIOD_HOURS;
export const JUPITER_ROTATION_SPEED =
  (Math.PI * 2) / JUPITER_ROTATION_PERIOD_HOURS;
export const SATURN_ROTATION_SPEED =
  (Math.PI * 2) / SATURN_ROTATION_PERIOD_HOURS;
export const URANUS_ROTATION_SPEED =
  (Math.PI * 2) / URANUS_ROTATION_PERIOD_HOURS;
export const NEPTUNE_ROTATION_SPEED =
  (Math.PI * 2) / NEPTUNE_ROTATION_PERIOD_HOURS;
export const MOON_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * MOON_ORBIT_PERIOD_DAYS);
export const EARTH_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * EARTH_ORBIT_PERIOD_DAYS);
export const MERCURY_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * MERCURY_ORBIT_PERIOD_DAYS);
export const VENUS_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * VENUS_ORBIT_PERIOD_DAYS);
export const MARS_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * MARS_ORBIT_PERIOD_DAYS);
export const JUPITER_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * JUPITER_ORBIT_PERIOD_DAYS);
export const SATURN_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * SATURN_ORBIT_PERIOD_DAYS);
export const URANUS_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * URANUS_ORBIT_PERIOD_DAYS);
export const NEPTUNE_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * NEPTUNE_ORBIT_PERIOD_DAYS);
export const IO_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * IO_ORBIT_PERIOD_DAYS);
export const EUROPA_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * EUROPA_ORBIT_PERIOD_DAYS);
export const GANYMEDE_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * GANYMEDE_ORBIT_PERIOD_DAYS);
export const CALLISTO_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * CALLISTO_ORBIT_PERIOD_DAYS);
export const TITAN_ORBIT_SPEED =
  (Math.PI * 2) / (EARTH_DAY_SECONDS * TITAN_ORBIT_PERIOD_DAYS);

export const EARTH_AXIAL_TILT = THREE.MathUtils.degToRad(23.44);
export const MERCURY_AXIAL_TILT = THREE.MathUtils.degToRad(0.03);
export const VENUS_AXIAL_TILT = THREE.MathUtils.degToRad(177.36);
export const MARS_AXIAL_TILT = THREE.MathUtils.degToRad(25.19);
export const JUPITER_AXIAL_TILT = THREE.MathUtils.degToRad(3.13);
export const SATURN_AXIAL_TILT = THREE.MathUtils.degToRad(26.73);
export const URANUS_AXIAL_TILT = THREE.MathUtils.degToRad(97.77);
export const NEPTUNE_AXIAL_TILT = THREE.MathUtils.degToRad(28.32);
export const MOON_ORBIT_INCLINATION = THREE.MathUtils.degToRad(5.145);
export const MERCURY_ORBIT_INCLINATION = THREE.MathUtils.degToRad(7.0);
export const VENUS_ORBIT_INCLINATION = THREE.MathUtils.degToRad(3.39);
export const MARS_ORBIT_INCLINATION = THREE.MathUtils.degToRad(1.85);
export const JUPITER_ORBIT_INCLINATION = THREE.MathUtils.degToRad(1.304);
export const SATURN_ORBIT_INCLINATION = THREE.MathUtils.degToRad(2.485);
export const URANUS_ORBIT_INCLINATION = THREE.MathUtils.degToRad(0.773);
export const NEPTUNE_ORBIT_INCLINATION = THREE.MathUtils.degToRad(1.77);
export const IO_ORBIT_INCLINATION = THREE.MathUtils.degToRad(0.04);
export const EUROPA_ORBIT_INCLINATION = THREE.MathUtils.degToRad(0.47);
export const GANYMEDE_ORBIT_INCLINATION = THREE.MathUtils.degToRad(0.2);
export const CALLISTO_ORBIT_INCLINATION = THREE.MathUtils.degToRad(0.19);
export const TITAN_ORBIT_INCLINATION = THREE.MathUtils.degToRad(0.34854);

export const REAL_SUN_DISTANCE_RATIO = 23455;
export const REAL_SUN_RADIUS_RATIO = 109;
export const SUN_DISTANCE_COMPRESSION = 0.00175;
export const SUN_RADIUS_COMPRESSION = 0.012;

export const SUN_DISTANCE = REAL_SUN_DISTANCE_RATIO * SUN_DISTANCE_COMPRESSION;
export const SUN_POSITION = new THREE.Vector3(-8.5, 2.8, -SUN_DISTANCE);
export const SUN_RADIUS = REAL_SUN_RADIUS_RATIO * SUN_RADIUS_COMPRESSION;
export const SUN_DISTANCE_COMPRESS_FACTOR = Math.round(
  1 / SUN_DISTANCE_COMPRESSION,
);

export const EARTH_ORBIT_LOCAL_OFFSET = new THREE.Vector3(
  -SUN_POSITION.x,
  0,
  -SUN_POSITION.z,
);
export const MERCURY_ORBIT_LOCAL_OFFSET =
  EARTH_ORBIT_LOCAL_OFFSET.clone().multiplyScalar(MERCURY_ORBIT_DISTANCE_RATIO);
export const VENUS_ORBIT_LOCAL_OFFSET =
  EARTH_ORBIT_LOCAL_OFFSET.clone().multiplyScalar(VENUS_ORBIT_DISTANCE_RATIO);
export const MARS_ORBIT_LOCAL_OFFSET =
  EARTH_ORBIT_LOCAL_OFFSET.clone().multiplyScalar(MARS_ORBIT_DISTANCE_RATIO);
export const JUPITER_ORBIT_LOCAL_OFFSET =
  EARTH_ORBIT_LOCAL_OFFSET.clone().multiplyScalar(JUPITER_ORBIT_DISTANCE_RATIO);
export const SATURN_ORBIT_LOCAL_OFFSET =
  EARTH_ORBIT_LOCAL_OFFSET.clone().multiplyScalar(SATURN_ORBIT_DISTANCE_RATIO);
export const URANUS_ORBIT_LOCAL_OFFSET =
  EARTH_ORBIT_LOCAL_OFFSET.clone().multiplyScalar(URANUS_ORBIT_DISTANCE_RATIO);
export const NEPTUNE_ORBIT_LOCAL_OFFSET =
  EARTH_ORBIT_LOCAL_OFFSET.clone().multiplyScalar(NEPTUNE_ORBIT_DISTANCE_RATIO);
export const JUPITER_RADIUS = EARTH_RADIUS * JUPITER_RADIUS_RATIO;
export const SATURN_RADIUS = EARTH_RADIUS * SATURN_RADIUS_RATIO;
export const IO_ORBIT_RADIUS =
  JUPITER_RADIUS * 5.905 * JUPITER_MOON_DISTANCE_COMPRESSION;
export const EUROPA_ORBIT_RADIUS =
  JUPITER_RADIUS * 9.396 * JUPITER_MOON_DISTANCE_COMPRESSION;
export const GANYMEDE_ORBIT_RADIUS =
  JUPITER_RADIUS * 14.989 * JUPITER_MOON_DISTANCE_COMPRESSION;
export const CALLISTO_ORBIT_RADIUS =
  JUPITER_RADIUS * 26.364 * JUPITER_MOON_DISTANCE_COMPRESSION;
export const TITAN_ORBIT_RADIUS =
  SATURN_RADIUS * 20.273 * SATURN_MOON_DISTANCE_COMPRESSION;

export const TEXTURES = {
  earthDay: "/textures/earth_day.jpg",
  earthNormal: "/textures/earth_normal.jpg",
  earthSpecular: "/textures/earth_specular.jpg",
  moon: "/textures/moon.jpg",
  mercury: "/textures/mercury_albedo.jpg",
  venus: "/textures/venus.jpg",
  venusClouds: "/textures/venus_clouds.jpg",
  mars: "/textures/mars.jpg",
  jupiter: "/textures/jupiter.jpg",
} as const;
